services:
  backend:
    build:
      context: ./server
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=${MONGO_URI}
    volumes:
      - ./server:/usr/src/server
      - ./temp:/usr/src/server/temp
    depends_on:
      - mongo

  frontend:
    build:
      context: ./client
    ports:
      - "5173:80"
    depends_on:
      - backend

  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data:
